targetScope = 'resourceGroup'

@description('Azure Developer CLI environment name (maps to azd-env-name tag).')
param environmentName string
@description('Azure region for all resources.')
param location string = resourceGroup().location
@description('Service name used for azd-service-name tag on Container Apps.')
param serviceName string = 'api'
@description('Optional tags applied to every resource.')
param tags object = {}
@description('Administrator password for PostgreSQL flexible server. Generated by preprovision hook if not provided.')
#disable-next-line secure-secrets-in-params // Auto-generated by hook; @secure() would prompt before hook runs
param postgresAdminPassword string = ''
@description('Password for the application database user (todo_user). Generated by preprovision hook if not provided.')
#disable-next-line secure-secrets-in-params // Auto-generated by hook; @secure() would prompt before hook runs
param todoDbPassword string = ''
@description('Application database user name.')
param todoDbUser string = 'todo_user'
@description('Container image repository path inside ACR (e.g., fastapi-reference-arch/api-dev).')
param imageRepository string = 'fastapi-reference-arch/api-dev'
@description('Container image tag to deploy (e.g., git SHA or dev).')
param imageTag string = 'latest'
@description('Optional full image reference (registry/repo:tag). When set, overrides repository/tag concatenation. Defaults to public sample image to allow first provision before custom image exists.')
param image string = 'mcr.microsoft.com/azuredocs/containerapps-helloworld:latest'
@description('Optional array of environment variables applied to the container app. Each entry should include name/value or name/secretRef.')
param environmentVariables array = []

var resourceToken = uniqueString(subscription().id, resourceGroup().id, location, environmentName)
var baseTags = union(tags, {
  'azd-env-name': environmentName
})
var todoDbPasswordSecretUrl = '${keyVaultModule.outputs.keyVaultUri}secrets/todo-db-password'

module identityModule './modules/identity.bicep' = {
  params: {
    location: location
    environmentName: environmentName
    resourceToken: resourceToken
    tags: baseTags
  }
}

module registryModule './modules/registry.bicep' = {
  params: {
    location: location
    environmentName: environmentName
    resourceToken: resourceToken
    tags: baseTags
  }
}

module monitoringModule './modules/monitoring.bicep' = {
  params: {
    location: location
    environmentName: environmentName
    resourceToken: resourceToken
    tags: baseTags
  }
}

module postgresModule './modules/postgres.bicep' = {
  params: {
    location: location
    environmentName: environmentName
    resourceToken: resourceToken
    tags: baseTags
    administratorPassword: postgresAdminPassword
    publicNetworkAccess: 'Enabled'
  }
}

module keyVaultModule './modules/keyvault.bicep' = {
  params: {
    location: location
    environmentName: environmentName
    resourceToken: resourceToken
    tags: baseTags
    userAssignedIdentityPrincipalId: identityModule.outputs.principalId
    todoDbPassword: todoDbPassword
  }
}

module acaModule './modules/aca.bicep' = {
  params: {
    location: location
    environmentName: environmentName
    resourceToken: resourceToken
    tags: baseTags
    serviceName: serviceName
    logAnalyticsCustomerId: monitoringModule.outputs.logAnalyticsCustomerId
    logAnalyticsWorkspaceId: monitoringModule.outputs.logAnalyticsId
    registryLoginServer: registryModule.outputs.loginServer
    userAssignedIdentityId: identityModule.outputs.identityId
    secrets: [
      {
        name: 'db-password'
        keyVaultUrl: todoDbPasswordSecretUrl
        identity: identityModule.outputs.identityId
      }
    ]
    imageRepository: imageRepository
    imageTag: imageTag
    image: image
    environmentVariables: concat([
      {
        name: 'DB_AUTH_MODE'
        value: 'password'
      }
      {
        name: 'DATABASE_HOST'
        value: postgresModule.outputs.fullyQualifiedDomainName
      }
      {
        name: 'DATABASE_PORT'
        value: '5432'
      }
      {
        name: 'DATABASE_NAME'
        value: 'postgres'
      }
      {
        name: 'DATABASE_USER'
        value: todoDbUser
      }
      {
        name: 'DATABASE_PASSWORD'
        secretRef: 'db-password'
      }
      {
        name: 'APPLICATIONINSIGHTS_CONNECTION_STRING'
        value: monitoringModule.outputs.appInsightsConnectionString
      }
      {
        name: 'APP_ENV'
        value: environmentName
      }
      {
        name: 'LOG_LEVEL'
        value: 'INFO'
      }
    ], environmentVariables)
  }
}

module rbacModule './modules/rbac.bicep' = {
  params: {
    acrId: registryModule.outputs.registryId
    userAssignedIdentityPrincipalId: identityModule.outputs.principalId
  }
}

output RESOURCE_GROUP_ID string = resourceGroup().id
output AZURE_CONTAINER_REGISTRY_ENDPOINT string = registryModule.outputs.loginServer
output CONTAINER_APP_FQDN string = acaModule.outputs.containerAppUrl
output CONTAINER_APP_ID string = acaModule.outputs.containerAppId
output POSTGRES_FQDN string = postgresModule.outputs.fullyQualifiedDomainName
output POSTGRES_DB string = 'postgres'
output MANAGED_IDENTITY_CLIENT_ID string = identityModule.outputs.clientId
output MANAGED_IDENTITY_PRINCIPAL_ID string = identityModule.outputs.principalId
output KEYVAULT_NAME string = keyVaultModule.outputs.keyVaultName
output KEYVAULT_URI string = keyVaultModule.outputs.keyVaultUri
output APPLICATIONINSIGHTS_CONNECTION_STRING string = monitoringModule.outputs.appInsightsConnectionString
